### ISSUE TITLE
Renew more than a week out

### ISSUE THREAD

**Issue by mholt** [dkumor/acmewrapper#1]
Cool project! Let me suggest that certificates be renewed more than one week out. I and Let's Encrypt recommend at least 30 days. Some current rate limits last a whole week, so attempting an early renewal can help prevent expiration if rate limits are hit.

**Comment by dkumor** [comment]
This is a configuration option, but I will make the default 30 days. Thanks!

PS: Caddy's Let's Encrypt code was very useful in getting this working!
