### ISSUE TITLE
Use time.Duration instead of int64

### ISSUE THREAD

**Issue by jpillora** [dkumor/acmewrapper#4]
Not sure if the use of `int64` was on purpose, though it would mean users could accidently provide negative times, `time.Duration` would solve this (and would also be idiomatic Go).

I think now would be best time to make API breaking changes since it's early days of this project so there won't be too many users yet. Also, I'm sure most people just leave defaults, so they won't be affected by the `Config` type change. Otherwise can close.

**Comment by dkumor** [comment]
Totally agree. Originally I wanted int since it works nicely with json marshalling, and I assumed that duration marshals to nanoseconds which would look awkward in a config file.

Since the project has existed for 4 days, I doubt anyone had time to depend on the ints.

**Comment by dkumor** [comment]
Nevertheless a notice in the readme won't hurt

**Comment by jpillora** [comment]
Awesome :+1:
