### ISSUE TITLE
New Certificate isn't generated after domain change.

### ISSUE THREAD

**Issue by chespinoza** [dkumor/acmewrapper#8]
How can I remove an existing certificate for a server? 

I tested a server with one domain, and then I tried with another domain, but the old domain certificate is alive yet , are there a way to force a domain change? I did the change into the code but doesn't work.

ie: 
first run with:
Domains: []string{"example.com","www.example.com"} 
then
Domains: []string{"example2.com","www.example2.com"}

and the server remains showing the example.com domain certificate and doesn't generate a new certificate for the new domain.

**Comment by chespinoza** [comment]
Sorry, I just fix the problem simply deleting the key and cert (reg and pem) files and running again my app.

**Comment by dkumor** [comment]
This is a bug - acmewrapper only checks for existence of certificates on startup, but not the domain. I'll see if I can fix it some time today.

**Comment by dkumor** [comment]
Can you confirm that the issue is now fixed?

**Comment by chespinoza** [comment]
Ok let me check again, thanks

**Comment by chespinoza** [comment]
Confirmed! Thanks and sorry for the delay.

**Comment by dkumor** [comment]
:)
